#!/bin/bash
DEPLOY_SOURCE=$1

if [[ "$DEPLOY_SOURCE" = "github" ]]; then
    # activate maintenance mode
    php artisan down

    # update source code
    git pull
    echo "Codebase updated"

    # update PHP dependencies
    export COMPOSER_HOME='/tmp/composer'
    composer install --no-interaction --no-dev --prefer-dist

else
    # Install frontend assets
    yarn

    yarn run production
fi

# update database
php artisan migrate --force

# stop maintenance mode
php artisan up

echo "Deploy script completed"
